### ISSUE TITLE
optimize.newton fail to converge

### ISSUE THREAD

**Issue by yaojunr** [bbuing9/DARP#4]
hello, i have used darp on my own dataset, but while training, in `opt_solver`, it raise an error that `Failed to converge after 30 iterations, value is 466315.4184961797.` How can i solve this? Thank you.

**Comment by bbuing9** [comment]
Hi, in my guess, the possible reasons for the mentioned error and the corresponding solutions are as follow:

1. “Not enough iterations or too high threshold”: If the number of unlabeled is much large or the probability of pseudo-labels is too over-confident, the given number of iterations might be not enough or threshold ("tol" in the code), might be too strict. Simply, let increase the number of iterations (num_iter &  num_newton) and increase the value of the threshold.

2. “Wrong target distribution”: If the summation of target distribution (targeted # of unlabeled data) is much different with the summation of pseudo-labels (actual # of unlabeled data), then such error can happen as they can’t be matched. So please check the used target distribution carefully.

I hope that these answers are working for you, thanks :)
