### ISSUE TITLE
CIfar100_Codes

### ISSUE THREAD

**Issue by ZJUJeffLai** [bbuing9/DARP#6]
Hi, 

Could you also share the codes on how you split cifar 100 and stl-10 dataset?

Many thanks,
Jeff

**Comment by bbuing9** [comment]
Hi, 

Previously, I personally replied to your e-mails related to this issue. 

Now, I update those parts in this repository (dataset/remix_cifar100.py, dataset/remix_stl.py)  

Thanks,
Jaehyung
