### ISSUE TITLE
Mixmatch on cifar-100 and stl-10

### ISSUE THREAD

**Issue by abababa-ai** [bbuing9/DARP#7]
It is very nice of you to provide the results on cifar-10, can you please provide the python code for Mixmatch on cifar-100 and stl-10? Because we are not able to reproduce the results on these two datasets. Thank you so much!

**Comment by abababa-ai** [comment]
To add to this, can you also give me the python code for fixmatch on these two data?

**Comment by bbuing9** [comment]
Thanks for your interest in our work.

Now, the overall codes are integrated among different datasets and semi-supervised methods. 

I hope that this will be helpful for your project.

Best,
Jaehyung
