### ISSUE TITLE
Respect authors:

### ISSUE THREAD

**Issue by lixiaopang221** [bbuing9/DARP#8]
Hello,  I have a question about the code. where is the file that is named 'progress.bar'?  You mentioned the file name in the 'utils/__init__.py'.

**Comment by bbuing9** [comment]
Hi, 'progress.bar' is actually from the package. Hence, you need to install it via 'pip install progress'. I'll add about this in readme file. Thx!

**Comment by lixiaopang221** [comment]
ok, thanks!
