### ISSUE TITLE
Precision Calculation

### ISSUE THREAD

**Issue by thomascong121** [bbuing9/DARP#9]
Hi, Thanks for the great work, I am really interested in your paper and recently tried to reimplement the codes. However, I am a bit confused about the metric calculation, especially balanced accuracy (bACC), I understand that bACC = (Sensitivity + Specificity) / 2, but it seems like the way you are calculating the bACC is just the top-1 accuracy. Is this a mistake?

**Comment by bbuing9** [comment]
Hi, this is due to that the used datasets (CIFAR and STL) have class-balanced test distributions. 

If the class distribution is imbalanced, then bACC is different from top-1 ACC as you mentioned. 

However, when the class distribution is balanced, both metrics become the same. 

Thanks,
Jaehyung
